Repository WORK-NECTOR/OFFIZZ-FE, pull requests merged in 2024-09, with the labels that each got.

#15 OFZ-26 fix: api 엔드포인트 오류 해결 및 지역 '강원권' 추가
  next.config.mjs
  package-lock.json
  src/api/office/getOffice.ts
  src/api/office/searchOffice.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Button/SelectButton/SelectButton.stories.ts
  src/components/Header/Header.tsx
  src/constants/office.ts
  src/lib/registry.tsx
  src/store/useMenuStore.ts
  src/store/userLocation.ts
Labels: 🐞BugFix

#16 OFZ-26 style: 카카오 로그인 화면 구현
  .eslintignore
  .eslintrc.json
  public/kakao-login.png
  public/offizz-logo.png
  src/api/axios.ts
  src/app/login/oauth2/code/kakao/page.tsx
  src/app/login/page.module.css
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/Header/Header.tsx
  src/constants/header.ts
  src/constants/main.ts
Labels: 🐞BugFix, 💅 style

#17 OFZ-34 feat: TimeRange 컴포넌트 개발
  .eslintrc.json
  package-lock.json
  public/ic-day.png
  public/ic-night.png
  src/components/TimeRange/TimeRange.stories.ts
  src/components/TimeRange/TimeRange.styled.ts
  src/components/TimeRange/TimeRange.tsx
  src/components/TimeRange/index.tsx
  src/types/timeRange.type.ts
  src/utils/formatTime.ts
Labels: ✨Feature

#19 OFZ-35 fix: 큐레이션 디자인 UI
  src/app/Information/quration/components/Category/Category.styled.ts
  src/app/Information/quration/components/Category/Category.tsx
  src/app/Information/quration/components/MainMsg/MainMsg.styled.ts
  src/app/Information/quration/components/MainMsg/MainMsg.tsx
  src/app/Information/quration/page.module.css
  src/app/Information/quration/page.tsx
  src/components/InFoBox/InFoBox.styled.ts
  src/components/InFoBox/InFoBox.tsx
  src/components/TitleDesc/TitleDesc.styled.ts
Labels: 💅 style

#18 OFZ-32 feat: 대시보드 홈 UI - 중간
  src/app/Information/components/MainCharacterBox/MainCharacterBox.styled.ts
  src/app/Information/components/MainCharacterBox/MainCharacterBox.tsx
  src/app/Information/components/MainCharacterBox/index.tsx
  src/app/Information/components/Recommend/Recommend.styled.ts
  src/app/Information/components/Recommend/Recommend.tsx
  src/app/Information/components/Recommend/index.tsx
  src/app/Information/page.module.css
  src/app/Information/page.tsx
  src/components/Tab/Tab.tsx
Labels: ✨Feature

#29 OFZ-45 fix: 헤더 및 로그인 로직 작업
  package-lock.json
  package.json
  src/api/axios.ts
  src/app/information/components/Recommend/Recommend.tsx
  src/app/layout.tsx
  src/app/login/oauth2/code/kakao/page.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/components/Header/Header.styled.ts
  src/components/Header/Header.tsx
  src/constants/header.ts
  src/hook/useAuth.ts
  src/lib/CookieProviderWrapper.tsx
  src/types/user.type.ts
Labels: 🐞BugFix, ✨Feature

#30 OFZ-46 feat: 메인 페이지 UI 개발(푸터)
  package-lock.json
  public/dotted-line.svg
  public/instagram-logo.png
  public/main-dashboard.png
  public/main-recap.png
  public/main-retrospective.png
  public/main-todo.png
  public/main-ywt.png
  src/app/page.module.css
  src/app/page.tsx
  src/components/FeatureInfo/FeatureInfo.stories.ts
  src/components/FeatureInfo/FeatureInfo.styled.ts
  src/components/FeatureInfo/FeatureInfo.tsx
  src/components/FeatureInfo/index.tsx
  src/components/Footer/Footer.styled.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/index.tsx
  src/constants/footer.ts
  src/types/feature.type.ts
Labels: ✨Feature, 🛠️ Refactor, 💅 style
