Repository WORK-NECTOR/OFFIZZ-FE, pull requests merged in 2024-08, with the labels that each got.

#7 OFZ-9 feat: Recap 페이지 디테일 중간pr
  src/app/globals.css
  src/app/recap/page.module.css
  src/app/recap/page.tsx
  src/components/RecapBox/RecapBox.styled.ts
  src/components/RecapBox/RecapBox.tsx
  src/types/recap.type.ts
  src/types/titleDesc.type.ts
Labels: ✨Feature, 💅 style

#8 OFZ-7 feat: SelectButton, OfficeAccordion 작업
  public/down-arrow.png
  src/app/page.tsx
  src/components/Badge/Badge.tsx
  src/components/Button/BasicButton/BasicButton.stories.ts
  src/components/Button/BasicButton/BasicButton.styled.ts
  src/components/Button/BasicButton/BasicButton.tsx
  src/components/Button/BasicButton/index.tsx
  src/components/Button/Button.tsx
  src/components/Button/SelectButton/SelectButton.stories.ts
  src/components/Button/SelectButton/SelectButton.styled.ts
  src/components/Button/SelectButton/SelectButton.tsx
  src/components/Button/SelectButton/index.tsx
  src/components/Button/index.tsx
  src/components/Info/OfficeInfo/OfficeInfo.styled.ts
  src/components/Info/OfficeInfo/OfficeInfo.tsx
  src/components/Info/OfficeInfo/index.tsx
  src/components/OfficeAccordion/OfficeAccordion.stories.ts
  src/components/OfficeAccordion/OfficeAccordion.styled.ts
  src/components/OfficeAccordion/OfficeAccordion.tsx
  src/components/OfficeAccordion/index.tsx
  src/components/TitleContent/TitleContent.stories.ts
  src/components/TitleContent/TitleContent.styled.ts
  src/components/TitleContent/TitleContent.tsx
  src/components/TitleContent/index.tsx
  src/constants/office.ts
  src/types/badge.type.ts
  src/types/button.type.ts
  src/types/info/officeInfo.type.ts
  src/types/office.type.ts
  src/types/selectButton.type.ts
  src/types/titleContent.type.ts
Labels: ✨Feature

#11 OFZ-7 feat: 지역 메뉴 개발
  src/app/page.module.css
  src/app/page.tsx
  src/components/Button/BasicButton/BasicButton.styled.ts
  src/components/Button/BasicButton/BasicButton.tsx
  src/components/Button/SelectButton/SelectButton.tsx
  src/components/OfficeAccordion/OfficeAccordion.tsx
  src/constants/main.ts
  src/constants/office.ts
  src/store/useRegionStore.ts
  src/types/button.type.ts
  src/types/selectButton.type.ts
Labels: ✨Feature, 💅 style

#12 OFZ-23 feat: react-query 세팅 추가
  src/api/axios.ts
  src/api/office/getOffice.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/services/office/useRecRegionOfficeQuery.ts
  src/services/queryClient.ts
  src/store/useUserStore.ts
Labels: ⚙️Setting, ✨Feature

#10 OFZ-22 feat: 리캡 Title, Non data일때 처리 & 정보제공 대시보드 UI
  public/heart.png
  src/app/Information/page.module.css
  src/app/Information/page.tsx
  src/app/Information/quration/components/Category/Category.styled.ts
  src/app/Information/quration/components/Category/Category.tsx
  src/app/Information/quration/components/Category/index.tsx
  src/app/Information/quration/components/MainMsg/MainMsg.styled.ts
  src/app/Information/quration/components/MainMsg/MainMsg.tsx
  src/app/Information/quration/components/MainMsg/index.tsx
  src/app/Information/quration/page.module.css
  src/app/Information/quration/page.tsx
  src/app/recap/page.module.css
  src/app/recap/page.tsx
  src/components/InFoBox/InFoBox.styled.ts
  src/components/InFoBox/InFoBox.tsx
  src/components/InFoBox/index.tsx
  src/components/RecapBox/RecapBox.tsx
  src/components/Tab/Tab.styled.ts
  src/components/Tab/Tab.tsx
  src/components/Tab/index.tsx
  src/components/TitleContent/TitleContent.stories.ts
  src/components/TitleContent/TitleContent.styled.ts
  src/components/TitleContent/TitleContent.tsx
  src/components/TitleContent/index.tsx
  src/components/TitleDesc/TitleDesc.styled.ts
  src/components/TitleDesc/TitleDesc.tsx
  src/types/titleDesc.type.ts
Labels: ✨Feature

#14 OFZ-25 feat: SearchBar 구현
  public/location.png
  public/search.png
  src/components/Bar/SearchBar/SearchBar.stories.ts
  src/components/Bar/SearchBar/SearchBar.styled.ts
  src/components/Bar/SearchBar/SearchBar.tsx
  src/components/Bar/SearchBar/index.tsx
  src/components/Button/BasicButton/BasicButton.styled.ts
  src/components/TitleContent/TitleContent.stories.ts
  src/components/TitleContent/TitleContent.styled.ts
  src/components/TitleContent/TitleContent.tsx
  src/components/TitleContent/index.tsx
  src/constants/recommend.ts
  src/types/searchBar.type.ts
Labels: ✨Feature

#13 OFZ-22 feat: 큐레이션 페이지 카카오맵 API 연결
  package-lock.json
  package.json
  src/api/office/searchOffice.ts
  src/app/Information/quration/page.tsx
  src/components/InFoBox/InFoBox.tsx
  src/components/KakaoMap/KakaoMap.tsx
  src/components/KakaoMap/use-kakao-loader.tsx
  src/components/OfficeAccordion/OfficeAccordion.tsx
  src/components/TitleDesc/TitleDesc.styled.ts
  src/hook/useDebounce.tsx
  src/services/office/useSearchOfficeQuery.ts
  src/store/userLocation.ts
  src/types/quration.type.ts
Labels: ✨Feature
