Repository WORK-NECTOR/OFFIZZ-FE, pull requests merged in 2024-10, with the labels that each got.

#32 OFZ-46 feat: 메인 페이지 추천 완성 및 라우터 연결
  src/app/favicon.ico
  src/app/page.module.css
  src/app/page.tsx
  src/components/OfficeAccordion/OfficeAccordion.tsx
  src/types/office.type.ts
Labels: ✨Feature, 💅 style

#33 OFZ-32 대시보드 개발
  public/charactor-laptop.png
  public/ic-sidebar-title.png
  public/plus-pink.png
  public/plus.png
  public/recap.png
  public/recommend-pink.png
  public/recommend.png
  public/time.png
  public/title.png
  public/todo-play.png
  src/app/Information/components/Todo/Todo.styled.ts
  src/app/Information/components/Todo/Todo.tsx
  src/app/Information/components/Todo/index.tsx
  src/app/focus/page.module.css
  src/app/focus/page.tsx
  src/app/information/components/MainCharacterBox/MainCharacterBox.styled.ts
  src/app/information/components/MainCharacterBox/MainCharacterBox.tsx
  src/app/information/components/MainCharacterBox/index.tsx
  src/app/information/components/Recommend/Recommend.styled.ts
  src/app/information/components/Recommend/Recommend.tsx
  src/app/information/components/Recommend/index.tsx
  src/app/information/components/Todo/Todo.styled.ts
  src/app/information/components/Todo/Todo.tsx
  src/app/information/components/Todo/index.tsx
  src/app/information/page.module.css
  src/app/information/page.tsx
  src/app/information/quration/components/Category/Category.styled.ts
  src/app/information/quration/components/Category/Category.tsx
  src/app/information/quration/components/Category/index.tsx
  src/app/information/quration/components/MainMsg/MainMsg.styled.ts
  src/app/information/quration/components/MainMsg/MainMsg.tsx
  src/app/information/quration/components/MainMsg/index.tsx
  src/app/information/quration/page.module.css
  src/app/information/quration/page.tsx
  src/components/Modal/Modal.styled.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/index.tsx
  src/components/Tab/Tab.styled.ts
  src/components/Tab/Tab.tsx
  src/store/useSelectTime.ts
  src/store/useSelectTodo.ts
  src/store/useTabStore.ts
Labels: ✨Feature

#45 OFZ-50 feat: 추천 페이지 완성
  src/api/office/getOfficeDetail.ts
  src/api/office/searchOffice.ts
  src/app/recommend/page.module.css
  src/app/recommend/page.tsx
  src/components/OfficeAccordion/OfficeAccordion.tsx
  src/components/PaginationBar/PaginationBar.tsx
  src/constants/office.ts
  src/services/office/useOfficeDetailQuery.ts
  src/services/office/useSearchOfficeQuery.ts
Labels: 🐞BugFix, ✨Feature, 💅 style

#46 OFZ-52 feat: 온보딩 api 연결 및 파비콘 변경
  src/api/onboarding/postOnboarding.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/onboarding/components/OnboardingEnd/OnboardingEnd.tsx
  src/components/Bar/SearchBar/SearchBar.tsx
  src/components/LocationItem/LocationItem.tsx
  src/services/onboarding/useOnboardingQuery.ts
  src/store/useOnboardingStore.ts
  src/store/useWorkationStore.ts
  src/types/searchPlace.type.ts
Labels: 🐞BugFix, ✨Feature, 💅 style

#47 OFZ-51 feat: 마이페이지 ui, focus 시간 로직 수정, 대시보드 vacation 모달 구현, 회고 ui
  public/camera.png
  public/done.png
  public/home.png
  public/leftarrow.png
  public/local.png
  public/my.png
  public/recomend.png
  public/retrospect.png
  public/rightarrow.png
  public/todo-vac.png
  src/api/office/searchOffice.ts
  src/app/focus/components/FocusSearchParams/FocusSearchParams.tsx
  src/app/focus/page.tsx
  src/app/information/components/Recommend/Recommend.styled.ts
  src/app/information/components/Recommend/Recommend.tsx
  src/app/information/components/Record/Record.styled.ts
  src/app/information/components/Record/Record.tsx
  src/app/information/components/Record/index.tsx
  src/app/information/components/Todo/Todo.tsx
  src/app/information/mypage/page.module.css
  src/app/information/mypage/page.tsx
  src/app/information/page.module.css
  src/app/information/page.tsx
  src/app/information/quration/components/Category/Category.tsx
  src/app/information/quration/page.module.css
  src/app/information/quration/page.tsx
  src/app/information/retrospect/page.module.css
  src/app/information/retrospect/page.tsx
  src/app/login/oauth2/code/kakao/page.tsx
  src/components/InFoBox/InFoBox.styled.ts
  src/components/InFoBox/InFoBox.tsx
  src/components/Modal/Modal.styled.ts
  src/components/Modal/Modal.tsx
  src/components/Tab/Tab.styled.ts
  src/components/Tab/Tab.tsx
  src/components/TodoModal/TodoModal.styled.ts
  src/components/TodoModal/TodoModal.tsx
  src/components/TodoModal/index.tsx
  src/services/office/useSearchOfficeQuery.ts
  src/store/useCategoryStore.ts
  src/store/useSelectDay.ts
  src/store/useSelectToggleStore.ts
  src/store/useTodoIdStore.ts
  src/types/quration.type.ts
  src/types/timeRange.type.ts
Labels: 🐞BugFix, ✨Feature, 💅 style

#50 hotFix : StaticImageData 추가
  src/app/information/components/Todo/Todo.tsx
Labels: 🚨Hotfix

#51 hotfix: Image태그 추가
  src/app/information/components/Todo/Todo.tsx
Labels: 🚨Hotfix

#52 hotfix: useSearchOfficesQuery의 filter 수정
  src/app/information/quration/page.tsx
Labels: 🚨Hotfix

#53 OFZ-56 fix: searchOffice -> searchWorkOffice 쿼리 수정
  src/api/office/searchWorkOffice.ts
  src/app/recommend/page.tsx
  src/services/office/useSearchWorkOfficeQuery.ts
Labels: 🚨Hotfix

#55 OfZ- 55 feat: 큐레이션페이지 api,토글 구현 & 자잘한 오류
  public/book.png
  public/v-like.png
  public/v-photo.png
  public/w-like.png
  src/api/office/searchOffice.ts
  src/app/focus/page.module.css
  src/app/information/components/Todo/Todo.tsx
  src/app/information/page.tsx
  src/app/information/quration/components/Category/Category.styled.ts
  src/app/information/quration/components/Category/Category.tsx
  src/app/information/quration/components/MainMsg/MainMsg.tsx
  src/app/information/quration/page.module.css
  src/app/information/quration/page.tsx
  src/components/InFoBox/InFoBox.tsx
  src/components/KakaoMap/KakaoMap.styled.ts
  src/components/KakaoMap/KakaoMap.tsx
  src/components/TodoModal/TodoModal.tsx
  src/services/office/useSearchOfficeQuery.ts
  src/store/useCategoryStore.ts
  src/store/userLocation.ts
  src/types/quration.type.ts
Labels: 🐞BugFix, ✨Feature, 💅 style

#59 OFZ-58 fix: 카카오 관련 오류 해결
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/Header/Header.tsx
Labels: 🚨Hotfix

#56 OFZ-57 feat: 리캡 api 연결
  src/app/information/components/Recommend/Recommend.styled.ts
  src/app/information/components/Record/Record.tsx
  src/app/information/quration/page.tsx
  src/app/recap/page.tsx
  src/components/InFoBox/InFoBox.tsx
  src/components/KakaoMap/KakaoMap.tsx
  src/components/RecapBox/RecapBox.styled.ts
  src/components/RecapBox/RecapBox.tsx
  src/types/recap.type.ts
Labels: ✨Feature, 💅 style

#61 OFZ-59 fix: RecapBox story 오류 해결
  src/components/RecapBox/RecapBox.stories.ts
Labels: 🚨Hotfix

#64 OFZ-53 fix: 배포 오류 해결
  src/app/recap/detail/components/BackNextBtn/BackNextBtn.tsx
  src/app/recap/detail/components/RecapWorkTime/RecapWorkTime.tsx
  src/app/recap/page.tsx
Labels: 🚨Hotfix

#65 OFZ-53 fix: 배포 오류 해결
  src/app/recap/detail/components/BackNextBtn/BackNextBtn.tsx
  src/app/recap/detail/components/RecapText/RecapText.tsx
  src/app/recap/detail/page.tsx
  src/app/recap/page.tsx
Labels: 🚨Hotfix

#67 OFZ-61 feat: 현재 진행 중인 워케이션이 있으면 /information 진입
  src/api/workation/getOngoing.ts
  src/app/page.tsx
  src/services/workation/useOngoingWorkation.ts
Labels: ✨Feature
